apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  namespace: alfiya-ajish
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: alfiya2821/factory:v3
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: app-secrets
          volumeMounts:
            - name: mqtt-cert
              mountPath: /app/certificate
              readOnly: true
            volumes:
              - name: mqtt-cert
                secret:
                  secretName: mqtt-cert-secret
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 80
        targetPort: 8081
      nodePort: 30082
  type: NodePort
