apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: alfiya-ajish
type: Opaque
stringData:
  MQTT_BROKER: g29a910b.ala.us-east-1.emqxsl.com
  MQTT_PORT: "8883"
  MQTT_USERNAME: emqx_user
  MQTT_PASSWORD: emqx_user@123
  CA_CERT_PATH: certificate/emqx_ca.crt

  MONGO_URI: mongodb+srv://alfiyaajish:alfi%402821@cluster0123.baa3brn.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0123
  REDIS_BROKER: rediss://default:AcPyAAIjcDE5OWZjZWM5ZDNhNGQ0YjRkYmI4NjhkM2VhMmEzNmY1MHAxMA@renewed-fowl-50162.upstash.io:6379/0
  ALERT_CHANNEL: alert_notifications

  ADMIN_SECRET_KEY: super_admin_secret_key
